openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/generate:
    post:
      summary: ''
      operationId: postApiGenerate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/retrieve/{id}':
    get:
      summary: ''
      operationId: getApiRetrieveId
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Number not found'
                properties:
                  message:
                    type: string
                    example: 'Number not found'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the retrieve.'
        example: tenetur
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
